### ISSUE TITLE
Certain file names cause a problem

### ISSUE THREAD

**Issue by veikk0** [BassThatHertz/video-quality-metrics#35] opened 2021-02-05 07:01 UTC
I'm having a problem with a file that has brackets in its name. I ran into the issue when using ntp mode with a reference input file that has brackets in the name.

How to reproduce: `python3 main.py -ntm -ovp "/home/veikk0/Videos/[test] test.mkv" -tvp "/home/veikk0/Videos/vtest.mkv" -vf scale=-2:480`

What happens when I execute the above command is that instead of the expected file name directory being created in the video-quality-metris directory, a directory named `(` is created. This will have subdirectories with names derived from the full -ovp input. So the directory structure is `video-quality-metrics/(/home/veikk0/Videos/vtest.mkv)/`.

The VMAF calculation itself finishes and there is a QualityMetrics.json file in the `vtest.mkv)` directory, but the process crashes with the following output:

    Traceback (most recent call last):
      File "main.py", line 191, in <module>
        transcoded_bitrate = provider.get_bitrate(args.transcoded_video_path)
      File "/home/veikk0/sources/video-quality-metrics/utils.py", line 71, in get_bitrate
        return f'{force_decimal_places(int(bitrate) / 1_000_000, decimal_places)} Mbps'
      File "/home/veikk0/sources/video-quality-metrics/utils.py", line 22, in force_decimal_places
        return '{:0.{dp}f}'.format(value, dp=decimal_places)
    ValueError: Format specifier missing precision

This is on Linux Mint 19.

**Comment by CrypticSignal** [comment] 2021-02-05 23:12
Fixed in commit 1e8be56.

The issue was not related to the filename. You can tell due to the error that you got:
```
File "/home/veikk0/sources/video-quality-metrics/utils.py", line 22, in force_decimal_places
    return '{:0.{dp}f}'.format(value, dp=decimal_places)
ValueError: Format specifier missing precision
```

The problem was that, on line 191 in main.py, the `get_bitrate` function (defined in utils.py) was only given the path of the transcoded video (`provider.get_bitrate(args.transcoded_video_path)`). This function can take two parameters, with the first parameter being the number of decimal places to use and the second parameter being the path of the video. Since only the path of the transcoded video was passed to the function, the `decimal places` parameter was being set to the path of the transcoded video, hence when trying to return ` '{:0.{dp}f}'.format(value, dp=decimal_places)` there was a `ValueError` as it was expecting `dp` to be a number.

Changing line 191 to `transcoded_bitrate = provider.get_bitrate(args.decimal_places, args.transcoded_video_path)` fixed this issue.

**Closed as completed** 2021-02-05 23:14 UTC

**Comment by veikk0** [comment] 2021-02-06 01:18
For some reason I just assumed it was a file name character problem. The program now successfully runs.

However, the strange directory structure is still being created (perhaps this side of the issue wasn't very clear in my report). I'll attach a screenshot of the directory structure below:

![vtest](https://user-images.githubusercontent.com/7808922/107104193-42499b00-6829-11eb-880a-34ad401aa3ae.png)

I believe the intended behavior is that a directory named `vtest.mkv` should be created in the project root, instead of this series of directories named after the input file path.

**Comment by CrypticSignal** [comment] 2021-02-06 01:41
@veikk0 
I should have paid more attention to your other issue. Apologies.

Outside of `-ntm` mode, the convention that I chose for the name of the output folder is the filename of the original video inside a pair of brackets. If I had successfully implemented this convention for `-ntm` mode, the name of your output folder would have been `(vtest.mkv)`.

Looking into this, I can see what the issue is. For `-ntm` mode, `args.transcoded_video_path` is used when creating the folder name, i.e. the whole path rather than just the filename. Let me fix this. I think I'll set the name of the output folder to be `[VQM] filename`.

Also, by the end of this weekend, I plan on adding the ability to specify an additional argument (`-o`) when running this program, allowing you specify a name to use for the output folder.

**Comment by CrypticSignal** [comment] 2021-02-06 01:50
Done. See commit 28d3cd6. Now, when using `-ntm` mode, the name of your output folder should be `[VQM] vtest.mkv`.

I will add the ability to specify a name for the output folder, whether you use `-ntm` mode or not, by the end of this weekend.

**Comment by CrypticSignal** [comment] 2021-02-07 23:55
The option to specify a name for the output folder has been added in commit https://github.com/CrypticSignal/video-quality-metrics/commit/91c69bcf6bfd367242bfa405e92f92668ea5a9c8.
